apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - name: blue-app
        image: hashicorp/http-echo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: [-listen=:8080, -text="I am blue"]
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: blue-app
  namespace: services
spec:
  selector:
    app: blue-app
  ports:
  - port: 8080
    targetPort: 8080

