apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - name: green-app
        image: hashicorp/http-echo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: [-listen=:8081, -text="I am green"]
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: green-app
  namespace: services
spec:
  selector:
    app: green-app
  ports:
  - port: 8081
    targetPort: 8081

